### ISSUE TITLE
Wrong highlight result on neovim

### ISSUE THREAD

**Issue by glyh** [314eter/tree-sitter-ocamllex#5] opened 2023-07-28 04:15 UTC
![image](https://github.com/314eter/tree-sitter-ocamllex/assets/12870742/ef3152a1-eafb-4c2e-b163-2fea334423e4)

**Comment by 314eter** [comment] 2023-07-28 07:13
It looks like the issue is before the part in the screenshow. Can you paste the full text of a file that reproduces the issue?

**Comment by glyh** [comment] 2023-07-28 08:49
https://github.com/mukul-rathi/bolt/blob/master/src/frontend/parsing/lexer.mll

**Comment by 314eter** [comment] 2023-07-28 09:15
This is what `tree-sitter highlight` does. Seems fine. Are you sure neovim is correctly configured to use tree-sitter-ocamllex?
![lexer0](https://github.com/314eter/tree-sitter-ocamllex/assets/890465/92eacc92-a65d-4d3a-bfb1-ed6a25901f97)
![lexer](https://github.com/314eter/tree-sitter-ocamllex/assets/890465/905f4f56-b971-4965-9963-dd79254a9342)

**Comment by glyh** [comment] 2023-07-28 09:23
![image](https://github.com/314eter/tree-sitter-ocamllex/assets/12870742/2d2e48dc-66bc-42d5-8c41-e158eeee892d)

Here's the TSPlayground info I got for it:
```
expression_item [0, 0] - [1, 13]
  application_expression [0, 0] - [1, 13]
    function: record_expression [0, 0] - [1, 6]
      field_expression [1, 2] - [1, 6]
        name: field_path [1, 2] - [1, 6]
          field_name [1, 2] - [1, 6]
    argument: constructor_path [1, 7] - [1, 13]
      constructor_name [1, 7] - [1, 13]
open_module [2, 2] - [2, 13]
  module_path [2, 7] - [2, 13]
    module_name [2, 7] - [2, 13]
exception_definition [4, 2] - [4, 33]
  constructor_declaration [4, 12] - [4, 33]
    constructor_name [4, 12] - [4, 23]
    type_constructor_path [4, 27] - [4, 33]
      type_constructor [4, 27] - [4, 33]
value_definition [6, 2] - [10, 47]
  let_binding [6, 6] - [10, 47]
    pattern: value_name [6, 6] - [6, 15]
    parameter [6, 16] - [6, 22]
      pattern: value_pattern [6, 16] - [6, 22]
    body: let_expression [7, 4] - [10, 47]
      value_definition [7, 4] - [7, 31]
        let_binding [7, 8] - [7, 31]
          pattern: value_name [7, 8] - [7, 11]
          body: field_get_expression [7, 14] - [7, 31]
            value_path [7, 14] - [7, 20]
              value_name [7, 14] - [7, 20]
            field_path [7, 21] - [7, 31]
              field_name [7, 21] - [7, 31]
      set_expression [8, 6] - [10, 47]
        field_get_expression [8, 6] - [8, 23]
          value_path [8, 6] - [8, 12]
            value_name [8, 6] - [8, 12]
          field_path [8, 13] - [8, 23]
            field_name [8, 13] - [8, 23]
        body: record_expression [9, 8] - [10, 47]
          value_path [9, 10] - [9, 13]
            value_name [9, 10] - [9, 13]
          field_expression [9, 19] - [9, 48]
            name: field_path [9, 19] - [9, 26]
              field_name [9, 19] - [9, 26]
            body: field_get_expression [9, 29] - [9, 48]
              value_path [9, 29] - [9, 35]
                value_name [9, 29] - [9, 35]
              field_path [9, 36] - [9, 48]
                field_name [9, 36] - [9, 48]
          field_expression [10, 19] - [10, 46]
            name: field_path [10, 19] - [10, 27]
              field_name [10, 19] - [10, 27]
            body: infix_expression [10, 30] - [10, 46]
              left: field_get_expression [10, 30] - [10, 42]
                value_path [10, 30] - [10, 33]
                  value_name [10, 30] - [10, 33]
                field_path [10, 34] - [10, 42]
                  field_name [10, 34] - [10, 42]
              operator: add_operator [10, 43] - [10, 44]
              right: number [10, 45] - [10, 46]
ERROR [11, 0] - [11, 1]
value_definition [13, 0] - [13, 23]
  let_binding [13, 4] - [13, 23]
    pattern: value_name [13, 4] - [13, 9]
    body: list_expression [13, 12] - [13, 23]
      infix_expression [13, 13] - [13, 22]
        left: character [13, 13] - [13, 16]
          character_content [13, 14] - [13, 15]
        operator: add_operator [13, 17] - [13, 18]
        right: character [13, 19] - [13, 22]
          character_content [13, 20] - [13, 21]
value_definition [14, 0] - [14, 23]
  let_binding [14, 4] - [14, 23]
    pattern: value_name [14, 4] - [14, 9]
    body: list_expression [14, 12] - [14, 23]
      infix_expression [14, 13] - [14, 22]
        left: character [14, 13] - [14, 16]
          character_content [14, 14] - [14, 15]
        operator: add_operator [14, 17] - [14, 18]
        right: character [14, 19] - [14, 22]
          character_content [14, 20] - [14, 21]
value_name [16, 4] - [16, 7]
application_expression [16, 10] - [16, 20]
  function: character [16, 10] - [16, 13]
    character_content [16, 11] - [16, 12]
  argument: labeled_argument [16, 13] - [16, 20]
    label_name [16, 15] - [16, 20]
add_operator [16, 20] - [16, 21]
value_name [17, 4] - [17, 6]
application_expression [17, 9] - [17, 34]
  function: parenthesized_expression [17, 9] - [17, 16]
    value_path [17, 10] - [17, 15]
      value_name [17, 10] - [17, 15]
  argument: parenthesized_expression [17, 17] - [17, 34]
    ERROR [17, 18] - [17, 30]
      value_path [17, 18] - [17, 23]
        value_name [17, 18] - [17, 23]
    character [17, 30] - [17, 33]
      character_content [17, 31] - [17, 32]
mult_operator [17, 34] - [17, 35]
value_name [18, 4] - [18, 22]
application_expression [18, 25] - [20, 14]
  function: list_expression [18, 25] - [18, 34]
    infix_expression [18, 26] - [18, 33]
      left: character [18, 26] - [18, 29]
        character_content [18, 27] - [18, 28]
      operator: add_operator [18, 29] - [18, 30]
      right: character [18, 30] - [18, 33]
        character_content [18, 31] - [18, 32]
  argument: value_path [20, 0] - [20, 3]
    value_name [20, 0] - [20, 3]
  argument: value_path [20, 4] - [20, 14]
    value_name [20, 4] - [20, 14]
rel_operator [20, 15] - [20, 16]
list_expression [20, 17] - [20, 27]
  application_expression [20, 18] - [20, 26]
    function: character [20, 18] - [20, 21]
      character_content [20, 19] - [20, 20]
    argument: character [20, 22] - [20, 26]
      character_content [20, 23] - [20, 25]
        escape_sequence [20, 23] - [20, 25]
add_operator [20, 27] - [20, 28]
or_pattern [21, 4] - [21, 34]
  or_pattern [21, 4] - [21, 25]
    value_name [21, 4] - [21, 11]
    ERROR [21, 12] - [21, 18]
      character [21, 14] - [21, 18]
        character_content [21, 15] - [21, 17]
          escape_sequence [21, 15] - [21, 17]
    character [21, 21] - [21, 25]
      character_content [21, 22] - [21, 24]
        escape_sequence [21, 22] - [21, 24]
  string [21, 28] - [21, 34]
    string_content [21, 29] - [21, 33]
      escape_sequence [21, 29] - [21, 31]
      escape_sequence [21, 31] - [21, 33]
parameter [23, 0] - [23, 4]
  pattern: value_pattern [23, 0] - [23, 4]
parameter [23, 5] - [23, 15]
  pattern: value_pattern [23, 5] - [23, 15]
ERROR [23, 18] - [24, 3]
  value_path [23, 18] - [23, 23]
    value_name [23, 18] - [23, 23]
string [24, 4] - [24, 7]
  string_content [24, 5] - [24, 6]
ERROR [24, 11] - [25, 7]
  constructor_path [24, 11] - [24, 17]
    constructor_name [24, 11] - [24, 17]
  string [25, 4] - [25, 7]
    string_content [25, 5] - [25, 6]
ERROR [25, 11] - [26, 7]
  constructor_path [25, 11] - [25, 17]
    constructor_name [25, 11] - [25, 17]
  string [26, 4] - [26, 7]
    string_content [26, 5] - [26, 6]
ERROR [26, 11] - [27, 7]
  constructor_path [26, 11] - [26, 17]
    constructor_name [26, 11] - [26, 17]
  string [27, 4] - [27, 7]
    string_content [27, 5] - [27, 6]
ERROR [27, 11] - [28, 7]
  constructor_path [27, 11] - [27, 17]
    constructor_name [27, 11] - [27, 17]
  string [28, 4] - [28, 7]
    string_content [28, 5] - [28, 6]
ERROR [28, 11] - [29, 7]
  constructor_path [28, 11] - [28, 16]
    constructor_name [28, 11] - [28, 16]
  string [29, 4] - [29, 7]
    string_content [29, 5] - [29, 6]
ERROR [29, 11] - [30, 7]
  constructor_path [29, 11] - [29, 14]
    constructor_name [29, 11] - [29, 14]
  string [30, 4] - [30, 7]
    string_content [30, 5] - [30, 6]
ERROR [30, 11] - [31, 7]
  constructor_path [30, 11] - [30, 16]
    constructor_name [30, 11] - [30, 16]
  string [31, 4] - [31, 7]
    string_content [31, 5] - [31, 6]
ERROR [31, 11] - [32, 7]
  constructor_path [31, 11] - [31, 20]
    constructor_name [31, 11] - [31, 20]
  string [32, 4] - [32, 7]
    string_content [32, 5] - [32, 6]
ERROR [32, 11] - [33, 7]
  constructor_path [32, 11] - [32, 16]
    constructor_name [32, 11] - [32, 16]
  string [33, 4] - [33, 7]
    string_content [33, 5] - [33, 6]
ERROR [33, 11] - [34, 7]
  constructor_path [33, 11] - [33, 15]
    constructor_name [33, 11] - [33, 15]
  string [34, 4] - [34, 7]
    string_content [34, 5] - [34, 6]
ERROR [34, 11] - [35, 7]
  constructor_path [34, 11] - [34, 16]
    constructor_name [34, 11] - [34, 16]
  string [35, 4] - [35, 7]
    string_content [35, 5] - [35, 6]
ERROR [35, 11] - [36, 7]
  constructor_path [35, 11] - [35, 15]
    constructor_name [35, 11] - [35, 15]
  string [36, 4] - [36, 7]
    string_content [36, 5] - [36, 6]
ERROR [36, 11] - [37, 7]
  constructor_path [36, 11] - [36, 14]
    constructor_name [36, 11] - [36, 14]
  string [37, 4] - [37, 7]
    string_content [37, 5] - [37, 6]
ERROR [37, 11] - [38, 7]
  constructor_path [37, 11] - [37, 14]
    constructor_name [37, 11] - [37, 14]
  string [38, 4] - [38, 7]
    string_content [38, 5] - [38, 6]
ERROR [38, 11] - [39, 7]
  constructor_path [38, 11] - [38, 17]
    constructor_name [38, 11] - [38, 17]
  string [39, 4] - [39, 7]
    string_content [39, 5] - [39, 6]
ERROR [39, 11] - [40, 8]
  constructor_path [39, 11] - [39, 17]
    constructor_name [39, 11] - [39, 17]
  string [40, 4] - [40, 8]
    string_content [40, 5] - [40, 7]
ERROR [40, 11] - [41, 8]
  constructor_path [40, 11] - [40, 14]
    constructor_name [40, 11] - [40, 14]
  string [41, 4] - [41, 8]
    string_content [41, 5] - [41, 7]
ERROR [41, 11] - [42, 7]
  constructor_path [41, 11] - [41, 17]
    constructor_name [41, 11] - [41, 17]
  string [42, 4] - [42, 7]
    string_content [42, 5] - [42, 6]
ERROR [42, 11] - [43, 8]
  constructor_path [42, 11] - [42, 27]
    constructor_name [42, 11] - [42, 27]
  string [43, 4] - [43, 8]
    string_content [43, 5] - [43, 7]
ERROR [43, 11] - [45, 9]
  constructor_path [43, 11] - [43, 19]
    constructor_name [43, 11] - [43, 19]
  string [45, 4] - [45, 9]
    string_content [45, 5] - [45, 8]
ERROR [45, 12] - [46, 9]
  constructor_path [45, 12] - [45, 15]
    constructor_name [45, 12] - [45, 15]
  string [46, 4] - [46, 9]
    string_content [46, 5] - [46, 8]
ERROR [46, 12] - [47, 11]
  constructor_path [46, 12] - [46, 15]
    constructor_name [46, 12] - [46, 15]
  string [47, 4] - [47, 11]
    string_content [47, 5] - [47, 10]
ERROR [47, 14] - [48, 9]
  constructor_path [47, 14] - [47, 19]
    constructor_name [47, 14] - [47, 19]
  string [48, 4] - [48, 9]
    string_content [48, 5] - [48, 8]
ERROR [48, 12] - [49, 14]
  constructor_path [48, 12] - [48, 15]
    constructor_name [48, 12] - [48, 15]
  string [49, 4] - [49, 14]
    string_content [49, 5] - [49, 13]
ERROR [49, 17] - [50, 13]
  constructor_path [49, 17] - [49, 25]
    constructor_name [49, 17] - [49, 25]
  string [50, 4] - [50, 13]
    string_content [50, 5] - [50, 12]
ERROR [50, 16] - [51, 12]
  constructor_path [50, 16] - [50, 23]
    constructor_name [50, 16] - [50, 23]
  string [51, 4] - [51, 12]
    string_content [51, 5] - [51, 11]
ERROR [51, 15] - [52, 11]
  constructor_path [51, 15] - [51, 21]
    constructor_name [51, 15] - [51, 21]
  string [52, 4] - [52, 11]
    string_content [52, 5] - [52, 10]
ERROR [52, 14] - [53, 11]
  constructor_path [52, 14] - [52, 19]
    constructor_name [52, 14] - [52, 19]
  string [53, 4] - [53, 11]
    string_content [53, 5] - [53, 10]
ERROR [53, 14] - [54, 22]
  constructor_path [53, 14] - [53, 19]
    constructor_name [53, 14] - [53, 19]
ERROR [54, 25] - [55, 16]
  constructor_path [54, 25] - [54, 37]
    constructor_name [54, 25] - [54, 37]
  string [55, 4] - [55, 16]
    string_content [55, 5] - [55, 15]
ERROR [55, 19] - [56, 12]
  constructor_path [55, 19] - [55, 30]
    constructor_name [55, 19] - [55, 30]
  string [56, 4] - [56, 12]
    string_content [56, 5] - [56, 11]
ERROR [56, 15] - [57, 11]
  constructor_path [56, 15] - [56, 21]
    constructor_name [56, 15] - [56, 21]
  string [57, 4] - [57, 11]
    string_content [57, 5] - [57, 10]
ERROR [57, 14] - [58, 10]
  constructor_path [57, 14] - [57, 19]
    constructor_name [57, 14] - [57, 19]
  string [58, 4] - [58, 10]
    string_content [58, 5] - [58, 9]
ERROR [58, 13] - [59, 17]
  constructor_path [58, 13] - [58, 17]
    constructor_name [58, 13] - [58, 17]
  string [59, 4] - [59, 17]
    string_content [59, 5] - [59, 16]
ERROR [59, 20] - [60, 12]
  constructor_path [59, 20] - [59, 31]
    constructor_name [59, 20] - [59, 31]
  string [60, 4] - [60, 12]
    string_content [60, 5] - [60, 11]
ERROR [60, 15] - [61, 9]
  constructor_path [60, 15] - [60, 21]
    constructor_name [60, 15] - [60, 21]
  string [61, 4] - [61, 9]
    string_content [61, 5] - [61, 8]
ERROR [61, 12] - [62, 10]
  constructor_path [61, 12] - [61, 20]
    constructor_name [61, 12] - [61, 20]
  string [62, 4] - [62, 10]
    string_content [62, 5] - [62, 9]
ERROR [62, 13] - [63, 10]
  constructor_path [62, 13] - [62, 22]
    constructor_name [62, 13] - [62, 22]
  string [63, 4] - [63, 10]
    string_content [63, 5] - [63, 9]
ERROR [63, 13] - [64, 14]
  constructor_path [63, 13] - [63, 22]
    constructor_name [63, 13] - [63, 22]
  string [64, 4] - [64, 14]
    string_content [64, 5] - [64, 13]
ERROR [64, 17] - [65, 10]
  constructor_path [64, 17] - [64, 25]
    constructor_name [64, 17] - [64, 25]
  string [65, 4] - [65, 10]
    string_content [65, 5] - [65, 9]
ERROR [65, 13] - [66, 11]
  constructor_path [65, 13] - [65, 17]
    constructor_name [65, 13] - [65, 17]
  string [66, 4] - [66, 11]
    string_content [66, 5] - [66, 10]
ERROR [66, 14] - [67, 11]
  constructor_path [66, 14] - [66, 19]
    constructor_name [66, 14] - [66, 19]
  string [67, 4] - [67, 11]
    string_content [67, 5] - [67, 10]
ERROR [67, 14] - [68, 8]
  constructor_path [67, 14] - [67, 19]
    constructor_name [67, 14] - [67, 19]
  string [68, 4] - [68, 8]
    string_content [68, 5] - [68, 7]
ERROR [68, 11] - [69, 10]
  constructor_path [68, 11] - [68, 13]
    constructor_name [68, 11] - [68, 13]
  string [69, 4] - [69, 10]
    string_content [69, 5] - [69, 9]
ERROR [69, 13] - [70, 9]
  constructor_path [69, 13] - [69, 17]
    constructor_name [69, 13] - [69, 17]
  string [70, 4] - [70, 9]
    string_content [70, 5] - [70, 8]
ERROR [70, 12] - [71, 10]
  constructor_path [70, 12] - [70, 15]
    constructor_name [70, 12] - [70, 15]
  string [71, 4] - [71, 10]
    string_content [71, 5] - [71, 9]
ERROR [71, 13] - [72, 12]
  constructor_path [71, 13] - [71, 17]
    constructor_name [71, 13] - [71, 17]
  string [72, 4] - [72, 12]
    string_content [72, 5] - [72, 11]
ERROR [72, 14] - [76, 7]
  constructor_path [72, 14] - [72, 20]
    constructor_name [72, 14] - [72, 20]
  record_expression [73, 15] - [73, 36]
    field_expression [73, 17] - [73, 27]
      name: field_path [73, 17] - [73, 27]
        field_name [73, 17] - [73, 27]
    ERROR [73, 28] - [73, 34]
  string [74, 4] - [74, 8]
    string_content [74, 5] - [74, 7]
  record_expression [74, 9] - [74, 44]
    field_expression [74, 11] - [74, 35]
      name: field_path [74, 11] - [74, 35]
        field_name [74, 11] - [74, 35]
    ERROR [74, 36] - [74, 42]
  string [75, 4] - [75, 8]
    string_content [75, 5] - [75, 7]
  record_expression [75, 9] - [75, 43]
    field_expression [75, 11] - [75, 34]
      name: field_path [75, 11] - [75, 34]
        field_name [75, 11] - [75, 34]
    ERROR [75, 35] - [75, 41]
ERROR [76, 10] - [77, 6]
  parenthesized_expression [76, 14] - [76, 52]
    application_expression [76, 15] - [76, 51]
      function: value_path [76, 15] - [76, 28]
        value_name [76, 15] - [76, 28]
      argument: parenthesized_expression [76, 29] - [76, 51]
        application_expression [76, 30] - [76, 50]
          function: value_path [76, 30] - [76, 43]
            module_path [76, 30] - [76, 36]
              module_name [76, 30] - [76, 36]
            value_name [76, 37] - [76, 43]
          argument: value_path [76, 44] - [76, 50]
            value_name [76, 44] - [76, 50]
ERROR [77, 9] - [80, 7]
  parenthesized_expression [77, 12] - [77, 34]
    application_expression [77, 13] - [77, 33]
      function: value_path [77, 13] - [77, 26]
        module_path [77, 13] - [77, 19]
          module_name [77, 13] - [77, 19]
        value_name [77, 20] - [77, 26]
      argument: value_path [77, 27] - [77, 33]
        value_name [77, 27] - [77, 33]
  character [78, 4] - [78, 7]
    character_content [78, 5] - [78, 6]
  record_expression [78, 8] - [78, 49]
    ERROR [78, 10] - [78, 40]
      parenthesized_expression [78, 22] - [78, 40]
        application_expression [78, 23] - [78, 39]
          function: value_path [78, 23] - [78, 36]
            module_path [78, 23] - [78, 29]
              module_name [78, 23] - [78, 29]
            value_name [78, 30] - [78, 36]
          argument: number [78, 37] - [78, 39]
    field_expression [78, 41] - [78, 47]
      name: field_path [78, 41] - [78, 47]
        field_name [78, 41] - [78, 47]
  record_expression [79, 12] - [79, 51]
    field_expression [79, 14] - [79, 23]
      name: field_path [79, 14] - [79, 23]
        field_name [79, 14] - [79, 23]
    ERROR [79, 24] - [79, 30]
    field_expression [79, 32] - [79, 42]
      name: field_path [79, 32] - [79, 42]
        field_name [79, 32] - [79, 42]
    ERROR [79, 43] - [79, 49]
ERROR [80, 10] - [88, 7]
  constructor_path [80, 10] - [80, 13]
    constructor_name [80, 10] - [80, 13]
  record_expression [81, 6] - [83, 50]
    ERROR [81, 8] - [82, 3]
      parenthesized_expression [81, 14] - [81, 82]
        application_expression [81, 15] - [81, 81]
          function: constructor_path [81, 15] - [81, 26]
            constructor_name [81, 15] - [81, 26]
          argument: parenthesized_expression [81, 27] - [81, 81]
            infix_expression [81, 28] - [81, 80]
              left: string [81, 28] - [81, 57]
                string_content [81, 29] - [81, 56]
              operator: concat_operator [81, 58] - [81, 59]
              right: application_expression [81, 60] - [81, 80]
                function: value_path [81, 60] - [81, 73]
                  module_path [81, 60] - [81, 66]
                    module_name [81, 60] - [81, 66]
                  value_name [81, 67] - [81, 73]
                argument: value_path [81, 74] - [81, 80]
                  value_name [81, 74] - [81, 80]
    field_expression [82, 4] - [82, 36]
      name: field_path [82, 4] - [82, 28]
        field_name [82, 4] - [82, 28]
      body: value_path [82, 31] - [82, 36]
        value_name [82, 31] - [82, 36]
    ERROR [83, 2] - [83, 30]
    field_expression [83, 32] - [83, 42]
      name: field_path [83, 32] - [83, 42]
        field_name [83, 32] - [83, 42]
    ERROR [83, 43] - [83, 49]
  record_expression [84, 8] - [87, 64]
    ERROR [84, 10] - [86, 3]
      constructor_path [84, 10] - [84, 13]
        constructor_name [84, 10] - [84, 13]
      record_expression [85, 6] - [85, 41]
        field_expression [85, 8] - [85, 32]
          name: field_path [85, 8] - [85, 32]
            field_name [85, 8] - [85, 32]
        ERROR [85, 33] - [85, 39]
    field_expression [86, 4] - [86, 35]
      name: field_path [86, 4] - [86, 27]
        field_name [86, 4] - [86, 27]
      body: value_path [86, 30] - [86, 35]
        value_name [86, 30] - [86, 35]
    ERROR [87, 2] - [87, 30]
    field_expression [87, 32] - [87, 55]
      name: field_path [87, 32] - [87, 55]
        field_name [87, 32] - [87, 55]
    ERROR [87, 56] - [87, 62]
ERROR [88, 10] - [90, 15]
  parenthesized_expression [88, 16] - [88, 89]
    application_expression [88, 17] - [88, 88]
      function: constructor_path [88, 17] - [88, 28]
        constructor_name [88, 17] - [88, 28]
      argument: parenthesized_expression [88, 29] - [88, 88]
        string [88, 30] - [88, 87]
          string_content [88, 31] - [88, 86]
  record_expression [89, 6] - [89, 40]
    field_expression [89, 8] - [89, 31]
      name: field_path [89, 8] - [89, 31]
        field_name [89, 8] - [89, 31]
    ERROR [89, 32] - [89, 38]
field_path [90, 16] - [90, 19]
  field_name [90, 16] - [90, 19]
ERROR [90, 22] - [91, 5]
  value_path [90, 22] - [90, 27]
    value_name [90, 22] - [90, 27]
string [91, 5] - [99, 9]
  string_content [91, 6] - [99, 8]
    escape_sequence [92, 5] - [92, 7]
    escape_sequence [93, 5] - [93, 7]
    escape_sequence [93, 10] - [93, 12]
    escape_sequence [93, 37] - [93, 39]
    escape_sequence [94, 5] - [94, 7]
    escape_sequence [95, 5] - [95, 7]
    escape_sequence [95, 36] - [95, 40]
    escape_sequence [96, 5] - [96, 7]
    escape_sequence [96, 36] - [96, 38]
    escape_sequence [97, 5] - [97, 7]
    escape_sequence [97, 36] - [97, 38]
    escape_sequence [98, 5] - [98, 7]
    escape_sequence [98, 36] - [98, 38]
argument: character [99, 9] - [99, 12]
  character_content [99, 10] - [99, 11]
ERROR [99, 12] - [99, 14]
```

Could you please provide a way to configure this correctly? All I do is just install ocamllex.

**Comment by glyh** [comment] 2023-07-28 09:26
Also, seems like amaanq added this to neovim-treesitter, ref: https://github.com/nvim-treesitter/nvim-treesitter/pull/4872. Do you mind take a look @amaanq ?Thank you.

**Comment by amaanq** [comment] 2023-07-28 09:29
Neovim uses reverse-precedence queries compared to upstream, so I wonder if that could be the issue. I didn't add the language, that'd be @undu (I just merged the commit)

**Comment by 314eter** [comment] 2023-07-28 09:29
It's using tree-sitter-ocaml to parse the mll file. That's a neovim configuration issue, so I will close this.

**Closed** 2023-07-28 09:29 UTC
